
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 6.4.0-3-amd64 - x86_64
...
