name: openMTPK Core

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest , macos-latest ]
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: initalize github repo
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: install deps
        run: | 
          sudo apt install lcov
          pip install gcovr
          mkdir build
      
      - name: setup CMake
        uses: ashutoshvarma/action-cmake-build@master
        with:
          build-dir: build
          cc: gcc
          cxx: g++
          build-type: Release
          install-build: true

      - name: build openMTPK lib
        run: | 
          LD_LIBRARY_PATH=/usr/local/lib
          mkdir build && cd build
          cmake ..
          make
          make install

      - name: openMTPK examples
        run: sh -x all.sh

