name: OCaml

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        ocaml-compiler:
          - 4.13.x
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: initalize github repo
        uses: actions/checkout@v2

      - name: Install OCaml Dependencies
        run: |
          sudo apt-get install ocaml &&
          sudo apt-get install opam &&
          opam init

      - name: Build OCaml API
        run: |
          cd OCaml/lib && ocamlc -c TEST_RM.ml
      
