name: Test Wheel Build

on:
  push:
    branches: [ main , dev , py_root_dir ]
  workflow_call:

jobs:
    test_build:
      runs-on: ubuntu-latest
      name: Test build source on x86_64 linux
      steps:
        - uses: actions/checkout@v3
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: "3.x"

        - name: install dependencies
          run: |
            pip install versioneer 
            pip install wheel
            sudo apt-get install swig

        - name: Build Wheel
          run: |
            python3 setup.py build_ext --inplace sdist bdist_wheel --plat-name=manylinux1_x86_64
            cd dist unzip *.whl

